name: Trigger auto deployment for authentik-worker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/authentik-worker-AutoDeployTrigger-230ae9bc-8c41-4e61-b1c6-0ce470ac5a86.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: authentik.azurecr.io
          username: ${{ secrets.AUTHENTIKWORKER_REGISTRY_USERNAME }}
          password: ${{ secrets.AUTHENTIKWORKER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: authentik.azurecr.io/authentik-worker:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AUTHENTIKWORKER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n authentik-worker -g ahbapps --server authentik.azurecr.io --username  ${{ secrets.AUTHENTIKWORKER_REGISTRY_USERNAME }} --password ${{ secrets.AUTHENTIKWORKER_REGISTRY_PASSWORD }}
            az containerapp update -n authentik-worker -g ahbapps --image authentik.azurecr.io/authentik-worker:${{ github.sha }}
